@extends('layouts.appfront')

@section('content')
    <p>hehe</p>
    <div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
    
                    <tr>
                        <th>ID</th>
                        <th>title</th>
                        <th>path</th>
                        <th>sortOrder</th>
                        <th>status</th>
                        <th>type</th>
                        <th>datas</th>
                        <th>cateid</th>
                    </tr>
                </thead>
            <tbody>
                
                <tr>
                    <td>1</td>
                    <td>dadad</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afafaf</td>
                    <td>afafafa</td>
                    <td>qw</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>dadad</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afafaf</td>
                    <td>afafafa</td>
                    <td>qw</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>dadad</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afafaf</td>
                    <td>afafafa</td>
                    <td>qw</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>dadad</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afafaf</td>
                    <td>afafafa</td>
                    <td>qw</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>dadad</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afafaf</td>
                    <td>afafafa</td>
                    <td>qw</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>dadad</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afafaf</td>
                    <td>afafafa</td>
                    <td>qw</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>dadad</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afafaf</td>
                    <td>afafafa</td>
                    <td>qw</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>dadad</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afafaf</td>
                    <td>afafafa</td>
                    <td>qw</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>dadad</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afafaf</td>
                    <td>afafafa</td>
                    <td>qw</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>dadad</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afafaf</td>
                    <td>afafafa</td>
                    <td>qw</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>dadad</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afafaf</td>
                    <td>afafafa</td>
                    <td>qw</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>dadad</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afaf</td>
                    <td>afafaf</td>
                    <td>afafaf</td>
                    <td>afafafa</td>
                    <td>qw</td>
                </tr>
                
            </tbody>
        </table>
    </div>
@endsection